<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE biblioteca [
  <!ELEMENT biblioteca (documentos)>
  <!ELEMENT documentos (libros, revistas, periodicos)>

  <!ELEMENT libros (libro, libro, libro)>
  <!ATTLIST libros id CDATA #REQUIRED>

  <!ELEMENT libro (titulo_libro, capitulos, indice_libro, sinopsis, numero_paginas_libro)>
  <!ATTLIST libro tipo_clase (novela|infantil|didactico) #REQUIRED>
  <!ELEMENT titulo_libro (#PCDATA)>
  <!ELEMENT capitulos (capitulo, capitulo, capitulo)>
  <!ELEMENT capitulo (titulo_capitulo, numero_paginas_capitulo, contenido)>
  <!ELEMENT titulo_capitulo (#PCDATA)>
  <!ELEMENT numero_paginas_capitulo (#PCDATA)>
  <!ELEMENT contenido (#PCDATA)>
  <!ATTLIST capitulo_libro contenido CDATA "Link al contenido">
  <!ELEMENT indice_libro (#PCDATA)>
  <!ELEMENT sinopsis (#PCDATA)>
  <!ELEMENT numero_paginas_libro (#PCDATA)>

  <!ELEMENT revistas (revista, revista, revista, revista, revista)>
  <!ATTLIST revistas id CDATA #REQUIRED>

  <!ELEMENT revista (titulo_revista, numero, indice_revista, secciones, numero_paginas_revista)>
  <!ATTLIST revista tipo_clase (informatica | corazon | coches | investigacion | otras) #REQUIRED>
  <!ELEMENT titulo_revista (#PCDATA)>
  <!ELEMENT numero (#PCDATA)>
  <!ELEMENT indice_revista (#PCDATA)>
  <!ELEMENT secciones (seccion, seccion)>
  <!ELEMENT seccion (numero_paginas_seccion, contenido_revista)>
  <!ELEMENT numero_paginas_seccion (#PCDATA)>
  <!ELEMENT contenido_revista (#PCDATA)>
  <!ATTLIST seccion contenido_revista CDATA "enlace info">
  <!ELEMENT numero_paginas_revista (#PCDATA)>



]>

<biblioteca>

  <documentos>
    <!-- Libros -->
    <libros id="L1234">
      <!-- libro de novela -->
      <libro tipo_clase="novela">
        <titulo_libro>La primera novela</titulo_libro>
        <capitulos>
          <capitulo>
            <titulo_capitulo>Primer capitulo</titulo_capitulo>
            <numero_paginas_capitulo>42</numero_paginas_capitulo>
            <contenido>Link al contenido</contenido>
          </capitulo>
          <capitulo>
            <titulo_capitulo>Segundo capitulo</titulo_capitulo>
            <numero_paginas_capitulo>32</numero_paginas_capitulo>
            <contenido>Link al contenido</contenido>
          </capitulo>
          <capitulo>
            <titulo_capitulo>Tercer capitulo</titulo_capitulo>
            <numero_paginas_capitulo>59</numero_paginas_capitulo>
            <contenido>Link al contenido</contenido>
          </capitulo>
        </capitulos>
        <indice_libro>
        1. Introduccion
        2. Desarrollo
        3.Conclusion
        </indice_libro>
        <sinopsis>Este libro es una novela</sinopsis>
        <numero_paginas_libro>133</numero_paginas_libro>
      </libro>

      <!-- libro infantil -->
      <libro tipo_clase="infantil">
        <titulo_libro>El libro infantil</titulo_libro>
        <capitulos>
          <capitulo>
            <titulo_capitulo>Primer capitulo</titulo_capitulo>
            <numero_paginas_capitulo>6</numero_paginas_capitulo>
            <contenido>Link al contenido</contenido>
          </capitulo>
          <capitulo>
            <titulo_capitulo>Segundo capitulo</titulo_capitulo>
            <numero_paginas_capitulo>12</numero_paginas_capitulo>
            <contenido>Link al contenido</contenido>
          </capitulo>
          <capitulo>
            <titulo_capitulo>Tercer capitulo</titulo_capitulo>
            <numero_paginas_capitulo>7</numero_paginas_capitulo>
            <contenido>Link al contenido</contenido>
          </capitulo>
        </capitulos>
        <indice_libro>
        1. Introduccion
        2. Desarrollo
        3.Conclusion
        </indice_libro>
        <sinopsis>Este libro es un libro infantil</sinopsis>
        <numero_paginas_libro>25</numero_paginas_libro>
      </libro>

      <!-- libro didactico -->
      <libro tipo_clase="didactico">
        <titulo_libro>Libro didactico</titulo_libro>
        <capitulos>
          <capitulo>
            <titulo_capitulo>Primer capitulo</titulo_capitulo>
            <numero_paginas_capitulo>40</numero_paginas_capitulo>
            <contenido>Link al contenido</contenido>
          </capitulo>
          <capitulo>
            <titulo_capitulo>Segundo capitulo</titulo_capitulo>
            <numero_paginas_capitulo>30</numero_paginas_capitulo>
            <contenido>Link al contenido</contenido>
          </capitulo>
          <capitulo>
            <titulo_capitulo>Tercer capitulo</titulo_capitulo>
            <numero_paginas_capitulo>20</numero_paginas_capitulo>
            <contenido>Link al contenido</contenido>
          </capitulo>
        </capitulos>
        <indice_libro>
        1. Introduccion
        2. Desarrollo
        3. Conclusion
        </indice_libro>
        <sinopsis>Este libro es totalmente didactico </sinopsis>
        <numero_paginas_libro>90</numero_paginas_libro>
      </libro>
    </libros>

    <!-- Revistas -->
    <revistas id="R">
      <!-- Ejemplo revista informatica -->
      <revista tipo_clase="informatica">
        <titulo_revista>Computer</titulo_revista>
        <numero>23</numero>
        <indice_revista>
          1.Hardware
          2.Software
          3.Apple
          4.Microsoft
        </indice_revista>
        <secciones>
          <seccion>
            <numero_paginas_seccion>12</numero_paginas_seccion>
            <contenido_revista>enlace info</contenido_revista>
          </seccion>
          <seccion>
            <numero_paginas_seccion>13</numero_paginas_seccion>
            <contenido_revista>enlace info</contenido_revista>
          </seccion>
        </secciones>
        <numero_paginas_revista>25</numero_paginas_revista>
      </revista>

      <!-- Ejemplo revista corazon -->
      <revista tipo_clase="corazon">
        <titulo_revista>Heart</titulo_revista>
        <numero>214</numero>
        <indice_revista>
          1.Titulo uno
          2.Titulo dos
          3.Titulo tres
          4.Titulo cautro
        </indice_revista>
        <secciones>
          <seccion>
            <numero_paginas_seccion>4</numero_paginas_seccion>
            <contenido_revista>enlace info</contenido_revista>
          </seccion>
          <seccion>
            <numero_paginas_seccion>2</numero_paginas_seccion>
            <contenido_revista>enlace info</contenido_revista>
          </seccion>
        </secciones>
        <numero_paginas_revista>6</numero_paginas_revista>
      </revista>

      <!-- Ejemplo revista coches -->
      <revista tipo_clase="coches">
        <titulo_revista>Cars</titulo_revista>
        <numero>2</numero>
        <indice_revista>
          1.Tesla
          2.Peugeot
        </indice_revista>
        <secciones>
          <seccion>
            <numero_paginas_seccion>6</numero_paginas_seccion>
            <contenido_revista>enlace info</contenido_revista>
          </seccion>
          <seccion>
            <numero_paginas_seccion>1</numero_paginas_seccion>
            <contenido_revista>enlace info</contenido_revista>
          </seccion>
        </secciones>
        <numero_paginas_revista>7</numero_paginas_revista>
      </revista>

      <!-- Ejemplo revista investigacion -->
      <revista tipo_clase="investigacion">
        <titulo_revista>Physics</titulo_revista>
        <numero>5</numero>
        <indice_revista>
          1.Fisica
          2.Ingenieria
          3.Medicina
        </indice_revista>
        <secciones>
          <seccion>
            <numero_paginas_seccion>5</numero_paginas_seccion>
            <contenido_revista>enlace info</contenido_revista>
          </seccion>
          <seccion>
            <numero_paginas_seccion>7</numero_paginas_seccion>
            <contenido_revista>enlace info</contenido_revista>
          </seccion>
        </secciones>
        <numero_paginas_revista>12</numero_paginas_revista>
      </revista>

      <!-- Ejemplo revista otras -->
      <revista tipo_clase="otras">
        <titulo_revista>The others</titulo_revista>
        <numero>9</numero>
        <indice_revista>
          1.Titulo uno
          2.Titulo dos
        </indice_revista>
        <secciones>
          <seccion>
            <numero_paginas_seccion>3</numero_paginas_seccion>
            <contenido_revista>enlace info</contenido_revista>
          </seccion>
          <seccion>
            <numero_paginas_seccion>2</numero_paginas_seccion>
            <contenido_revista>enlace info</contenido_revista>
          </seccion>
        </secciones>
        <numero_paginas_revista>5</numero_paginas_revista>
      </revista>
    </revistas>

    <!-- Periodicos -->
    <periodicos id="P1234">
      <!-- Ejemplo periodicio nacional -->
      <periodico tipo_clase="nacional" fecha_publi="12-4-2002">
        <secciones>
          <!-- ejemplo economia -->
          <seccion id="economica">
            <articulos>
              <articulo autor="Pepito">
                <contenido>Atributo que referencie hacia la info</contenido>
              </articulo>
            </articulos>
          </seccion>
          <!-- ejemplo opinion -->
          <seccion id="opinion">
            <articulos>
              <articulo autor="Bruno">
                <contenido>Atributo que referencie hacia la info</contenido>
              </articulo>
              <articulo autor="Bob">
                <contenido>Atributo que referencie hacia la info</contenido>
              </articulo>
            </articulos>
          </seccion>

          <!-- ejemplo deportes -->
          <seccion id="deportes">
            <articulos>
              <articulo autor="Roncero">
                <contenido>Atributo que referencie hacia la info</contenido>
              </articulo>
              <articulo autor="Alvaro">
                <contenido>Atributo que referencie hacia la info</contenido>
              </articulo>
            </articulos>
          </seccion>


          <!-- ejemplo nacional -->
          <seccion id="nacional">
            <articulos>
              <articulo autor="Alberto">
                <contenido>Atributo que referencie hacia la info</contenido>
              </articulo>
            </articulos>
          </seccion>

          <!-- ejemplo internacional -->
          <seccion id="internacional">
            <articulos>
              <articulo autor="Juan">
                <contenido>Atributo que referencie hacia la info</contenido>
              </articulo>
            </articulos>
          </seccion>

        </secciones>
      </periodico>

      <!-- Ejemplo Internacional -->
      <periodico tipo_clase="internacional" fecha_publi="12-4-2002">
        <secciones>
          <!-- ejemplo economia -->
          <seccion id="economica">
            <articulos>
              <articulo autor="Joe">
                <contenido>Atributo que referencie hacia la info</contenido>
              </articulo>
            </articulos>
          </seccion>
          <!-- ejemplo opinion -->
          <seccion id="Franz">
            <articulos>
              <articulo autor="Bruno">
                <contenido>Atributo que referencie hacia la info</contenido>
              </articulo>
              <articulo autor="Bob">
                <contenido>Atributo que referencie hacia la info</contenido>
              </articulo>
            </articulos>
          </seccion>

          <!-- ejemplo deportes -->
          <seccion id="deportes">
            <articulos>
              <articulo autor="Ali">
                <contenido>Atributo que referencie hacia la info</contenido>
              </articulo>
              <articulo autor="Sam">
                <contenido>Atributo que referencie hacia la info</contenido>
              </articulo>
            </articulos>
          </seccion>


          <!-- ejemplo nacional -->
          <seccion id="nacional">
            <articulos>
              <articulo autor="Charles">
                <contenido>Atributo que referencie hacia la info</contenido>
              </articulo>
            </articulos>
          </seccion>

          <!-- ejemplo internacional -->
          <seccion id="internacional">
            <articulos>
              <articulo autor="Peter">
                <contenido>Atributo que referencie hacia la info</contenido>
              </articulo>
            </articulos>
          </seccion>

        </secciones>
      </periodico>
    </periodicos>

  </documentos>
</biblioteca>
